Deprecate gometalinter and use golangcli-lint instead (#56)
*  Deprecate gometalinter and use golangcli-lint for lint

https://github.com/alecthomas/gometalinter has been deprecated and author suggest to use https://github.com/golangci/golangci-lint instead.

Migrate most of the linters to golangci-lint.

Remove original linter_config.json and add linter_config.yaml

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

* Fix Error return value of not checked problems in tests

errcheck will report issue if return value is not used. One example is

pkg/controller.v1beta1/mxnet/pod_test.go:66:10: Error return value of `ctr.Run` is not checked (errcheck)
		ctr.Run(testutil.ThreadCount, stopCh)
		       ^

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

* Update-codegen to update copyright header

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>